# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'CoffeeMaster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoffeeMaster
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'CodableFirebase'
  pod 'Mapbox-iOS-SDK', '~> 5.5'
  pod 'expanding-collection'
  
  target 'CoffeeMasterTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
#  target 'CoffeeMasterWatch Extension' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'Coffee Master Widget' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
